### ISSUE TITLE
registering new user

### ISSUE THREAD

**Issue by sumitpatel93** [androidneha/mern-admin-panel#2]
How can we register a new user, while local setup ? /register route gives err in css

**Comment by IsmaelHeredia** [comment]
Same error.

**Comment by dashingsuma** [comment]
anyone found the solution

**Comment by LuisTorres1992** [comment]
I have the same problem, I can not enter, where do I register a new user?

**Comment by ananthavel** [comment]
Same error.

**Comment by rverma540** [comment]
Can anyone  share the login details

**Comment by androidneha** [comment]
Hello everyone, as you all know that admin panel does not have register component/feature. You just have to enter one record manually in your database. For password you can use any online password hashing website.
